### PR TITLE
Keep Exceptions if replaceExisting=false

### PR DESCRIPTION
**Pull request by 6ff334e**
Exceptions were not kept if replaceExisting was set to false.

### CODE REVIEW

**Comment by anshooarora** [comment]
This, this is to retain the exceptions from the previous run, correct?

**Comment by 6ff334e** [comment]
@anshooarora Yes, with these changes exceptions from previous runs should be retained.

**Comment by 6ff334e** [comment]
Should I add a config parameter to enable this explicitly? Maybe not everybody wants to retain exceptions by default.

**Comment by anshooarora** [comment]
I think we should just make it a standard, it would be good for the user to know the past exceptions as well.

**Comment by anshooarora** [comment]
quick question - Is it going to show the old exception under the exceptions list (exceptions-view)?

**Comment by email2vimalraj** [comment]
I agree with @6ff334e. It should be a config parameter. User should enable on demand.

**Pull request merged**
