### PR TITLE
Added a method to add the screen shot image as base64 string in the report

### PR DESCRIPTION
**Pull request by email2vimalraj**
Currently, the extent report support to add the screen shot image as file. This PR proposes a new method to add the screen shot image as base64 string.

**Why?**
Most of the times, we send the report through email. This needs the image files also zipped together with the report html file. To avoid this, the user can use the base64 string of the png image file and add that in a report file using the method provided.
This solves the problem of email-able report also. 100% single report file.

Also, added the unit test package using which we can test the pieces of code. Currently, just added the unit test only for this method. I'll try to come up with unit tests for other methods in my future PRs.

### CODE REVIEW

**Comment by email2vimalraj** [comment]
Attached the sample report generated using the new method addBase64ScreenShot()
[report.html.zip](https://github.com/anshooarora/extentreports/files/182882/report.html.zip)

**Comment by email2vimalraj** [comment]
@anshooarora : Please review

**Comment by anshooarora** [comment]
Merged, this is a good addition.

**Comment by aonarun** [comment]
Hi Vimal,

Can you please share the code how you captured the snap using the Base64 and stored to a server. since am getting the snap in the report in my machine & not able to see the same in other machine. Am also having the same problem as you hava, while sharing the image files.

Thanks,
Arun

**Comment by moinuddin14** [comment]
@aonarun Here's the files he has added through this pull request. [https://github.com/anshooarora/extentreports-java/pull/384/commits/50c9ed8a376dd74fbd963651393c23da1577fe64](url)

**Pull request merged**
